# no se pudo implementar docker por que no halle la forma de iniciar una database con sqlserver
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: prueba-tecnica-api
    container_name: api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=my_db;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - backend

volumes:
  sqlserver_data:

networks:
  backend:
    driver: bridge
